on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    container: golang:1.23-bullseye
    env:
      GOFLAGS: -buildvcs=false
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v6.1.1
        if: github.ref != 'refs/heads/master'
        with:
          version: latest
          args: --timeout=5m --tests=false ./...
  test:
    runs-on: ubuntu-latest
    container: golang:1.23-bullseye
    services:
      postgres:
        image: postgres:14-bullseye
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_HOST_AUTH_METHOD: trust
    env:
      ENVIRONMENT: ci
    steps:
      - uses: actions/checkout@v4
      - run: environment=ci go test -json -coverprofile=/root/coverage.txt -covermode=atomic ./... > /root/test.json
      - run: cat /root/test.json
        if: always()
      - uses: guyarb/golang-test-annotations@v0.5.0
        if: always()
        with:
          test-results: /root/test.json
