on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.23-bullseye
    services:
      postgres:
        image: postgres:14-bullseye
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_HOST_AUTH_METHOD: trust
    env:
      ENVIRONMENT: ci
    steps:
      - uses: actions/checkout@v4
      - run: apt-get update && apt-get install curl openssl git openssh-client build-essential -y
      - run: go mod vendor
      - run: wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /source/
        if: github.ref != 'refs/heads/master'
      - run: cd /source && ./golangci-lint run ./... --timeout 3m
        if: github.ref != 'refs/heads/master'
      - run: cd /source && environment=ci go test -json -coverprofile=/root/coverage.txt -covermode=atomic ./... > /root/test.json
#      - name: Upload coverage report
#        uses: codecov/codecov-action@v3
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: /root/coverage.txt
#          flags: unittests
      - run: cat /root/test.json
        if: always()
      - uses: guyarb/golang-test-annotations@v0.5.0
        if: always()
        with:
          test-results: /root/test.json
